# =============================================================================
# Haven Platform — Root Module
# =============================================================================
# Shared infrastructure (network, SSH key) + module calls for each node.
# Consumes *.auto.tfvars.json generated by `strata build`.
#
# Wave 1: Hearth (Docker Compose — Caddy, Authentik, Vaultwarden, Infisical)
# Wave 2: Forge  (k3s — Immich, Gatus, apps)
# =============================================================================

# =============================================================================
# Locals
# =============================================================================

locals {
  # Hetzner resource names must be valid RFC 1123 hostnames (no underscores).
  # workspace_name from strata uses underscores (e.g. "haven_platform") — replace with hyphens.
  safe_name = replace(var.workspace_name, "_", "-")

  common_labels = merge(var.labels, {
    workspace   = var.workspace_name
    environment = var.environment
    managed_by  = "opentofu"
  })

  # Filter resources by type
  vm_resources = {
    for name, res in var.resources : name => res
    if res.type == "virtualmachine"
  }

  storagebox_resources = {
    for name, res in var.resources : name => res
    if res.type == "storagebox"
  }
}

# =============================================================================
# SSH Key (shared across all nodes)
# =============================================================================

resource "hcloud_ssh_key" "haven" {
  name       = "${local.safe_name}-deploy"
  public_key = var.HETZNER_PUBLIC_KEY
  labels     = local.common_labels
}

# =============================================================================
# Private Network (shared — Hearth <-> Forge communication)
# =============================================================================

resource "hcloud_network" "haven" {
  name     = "${local.safe_name}-net"
  ip_range = var.network_cidr
  labels   = local.common_labels
}

resource "hcloud_network_subnet" "haven" {
  network_id   = hcloud_network.haven.id
  type         = "cloud"
  network_zone = var.network_zone
  ip_range     = var.subnet_cidr
}

# =============================================================================
# Module — Hearth (Wave 1)
# =============================================================================

module "hearth" {
  source = "./modules/hearth"

  depends_on = [hcloud_network_subnet.haven]

  resource_config = local.vm_resources["haven_vm_hetzner_hearth"]
  firewall_config = var.firewalls[local.vm_resources["haven_vm_hetzner_hearth"].firewall]
  ssh_key_id      = hcloud_ssh_key.haven.id
  network_id      = hcloud_network.haven.id
  labels          = local.common_labels
  workspace_name  = var.workspace_name
}
