---
install_path: /opt/haven
compose_dir: /opt/haven/etc/compose
docker_compose_version: "2"
haven_user: root

haven_dirs:
  - /opt/haven/etc
  - /opt/haven/etc/compose
  - /opt/haven/var/data
  - /opt/haven/var/logs
  - /opt/haven/var/certs
