apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-upload
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.upload.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.upload.size }}
