apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}"
type: Opaque
stringData:
  foundry-username: "{{ .Values.env.FOUNDRY_USERNAME }}"
  foundry-password: "{{ .Values.env.FOUNDRY_PASSWORD }}"
  foundry-admin-key: "{{ .Values.env.FOUNDRY_ADMIN_KEY }}"
